server:
  port: 10010 # 网关端口约定10010

spring:
  application:
    name: springcloud-gateway # 服务名称
  cloud:
    nacos:
      server-addr: 192.168.200.130:8848 # nacos地址
    gateway:
      discovery:
        locator:
          enabled: true
      routes: # 网关路由配置
        - id: article-service # 路由id，自定义，只要唯一即可
          uri: lb://news-service-article # 路由的目标地址，lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/api/service-article/article/**, /api/service-article/portal/article/**, /api/service-article/comment/**
          filters:
            - RewritePath=/api/service-article(?<segment>.*),/$\{segment}

        - id: admin-service # 路由id，自定义，只要唯一即可
          uri: lb://news-service-admin # 路由的目标地址，lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/api/service-admin/adminMng/**, /api/service-admin/categoryMng/**, /api/service-admin/friendLinkMng/**
          filters:
            - RewritePath=/api/service-admin(?<segment>.*),/$\{segment}

        - id: files-service # 路由id，自定义，只要唯一即可
          uri: lb://news-service-files # 路由的目标地址，lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/api/service-files/fs/**
          filters:
            - RewritePath=/api/service-files(?<segment>.*),/$\{segment}

        - id: user-service # 路由id，自定义，只要唯一即可
          uri: lb://news-service-user # 路由的目标地址，lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/api/service-user/appUser/**, /api/service-user/fans/**, /api/service-user/passport/**, /api/service-user/user/**
          filters:
            - RewritePath=/api/service-user(?<segment>.*),/$\{segment}